name: Build Docker Images

on:
  push:
    tags:
      - 'v*'

jobs:
  build_image:
    name: Build and Push Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract branch and tag name
        id: extract_branch_tag
        shell: bash
        run: |
          BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
          IMAGE_TAG=$(echo "${GITHUB_REF#refs/tags/}")
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
          echo "IMAGE_TAG=$IMAGE_TAG"   >> $GITHUB_ENV
          echo "BUILD_CONTEXT=src/$BRANCH_NAME" >> $GITHUB_ENV # Set the correct context

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERRHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ${{ env.BUILD_CONTEXT }}
          push: true
          tags: |
            ${{ secrets.DOCKERRHUB_USERNAME }}/lilo-finance-manager-${{ env.BRANCH_NAME }}-service:${{ env.IMAGE_TAG }}
