name: Run Integration Tests

on:
  push:
    branches-ignore:
        - '*/*'
  pull_request:

jobs:
    test-messagery-integration:
        name: Run Integration Tests on Messagey
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.13
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v5
          with:
            version: latest
            enable-cache: true
            cache-suffix: "messagery"
            cache-dependency-glob: "src/common_utils/messagery/uv.lock"

        - name: Sync dependencies
          run: |
            cd src/common_utils/messagery
            uv sync --group test

        - name: Run Integration Tests
          run: |
            cd src/common_utils/messagery
            source .venv/bin/activate
            make integration-test
