name: Run Integration Tests

on:
  push:
    branches-ignore:
        - '*/*'
  pull_request:
    branches-ignore:
      - '*/*'

jobs:
    test-integration:
        name: Run Integration Tests on ${{ matrix.service }}
        runs-on: ubuntu-latest
        strategy:
          matrix:
            service:
              - common_utils/messagery
              - user_management
        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.13
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"

        - name: Get service base path
          id: service_path
          run: |
            echo "base_path=src/${{ matrix.service }}" >> $GITHUB_OUTPUT

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v5
          with:
            version: latest
            enable-cache: true
            cache-suffix: "integration-${{ matrix.service }}"
            cache-dependency-glob: "${{ steps.service_path.outputs.base_path }}/uv.lock"

        - name: Sync dependencies
          run: |
            cd "${{ steps.service_path.outputs.base_path }}"
            uv sync --group test

        - name: Run Integration Tests
          run: |
            cd "${{ steps.service_path.outputs.base_path }}"
            source .venv/bin/activate
            make integration-test
