name: Run Unit Tests

on: [push, pull_request]

jobs:
    test-messagery:
        name: Run Unit Tests on Messagery
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4

        - name: Set up Python 3.13
          uses: actions/setup-python@v5
          with:
            python-version: "3.13"

        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v5
          with:
            version: latest
            enable-cache: true
            cache-suffix: "messagery"
            cache-dependency-glob: "src/common_utils/messagery/uv.lock"

        - name: Sync dependencies
          run: |
            cd src/common_utils/messagery
            uv sync --all-groups

        - name: Run Linting
          run: |
            cd src/common_utils/messagery
            source .venv/bin/activate
            make lint

        - name: Run Mypy
          run: |
            cd src/common_utils/messagery
            source .venv/bin/activate
            make mypy

        - name: Run Unit Tests
          run: |
            cd src/common_utils/messagery
            source .venv/bin/activate
            make unit-test

    test-user-management:
      name: Run Unit Tests on User Management
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          version: latest
          enable-cache: true
          cache-suffix: "user-management"
          cache-dependency-glob: "src/user_management/uv.lock"

      - name: Sync dependencies
        run: |
          cd src/user_management
          uv sync --all-groups

      - name: Run Linting
        run: |
          cd src/user_management
          source .venv/bin/activate
          make lint

      - name: Run Mypy
        run: |
          cd src/user_management
          source .venv/bin/activate
          make mypy

      - name: Run Unit Tests
        run: |
          cd src/user_management
          source .venv/bin/activate
          make unit-test
